services:
  react-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
     - php
     - mysql
     - phpmyadmin
  php:
    build: ./php
    ports:
      - "9000:80"
    volumes:
      - ./public/arts:/var/www/html/public/arts
      - ./php:/var/www/html
      - php-vendor:/var/www/html/vendor
    depends_on:
      - mysql

  mysql:
    build: ./mysql
    environment:
      MYSQL_DATABASE: pkrim-art-gallery

volumes:
  react-art-volume:
  php-vendor: