services:
  react-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src  # Mount the React source code for live updates
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
     - php
     - mysql
     - phpmyadmin
  php:
    build: ./php
    ports:
      - "9000:80"
    volumes:
      - ./public/arts:/var/www/html/public/arts
      - ./php:/var/www/html  # Mount your PHP source code for development
      - php-vendor:/var/www/html/vendor  # Named volume for vendor directory
    depends_on:
      - mysql

  mysql:
    build: ./mysql
    environment:
      MYSQL_DATABASE: pkrim-art-gallery

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  react-art-volume:
  php-vendor: